// Package api holds the HTTP handlers and router (chi) for the Bia Energy
// backend — one file per resource, mounted here.
package api

import (
	"database/sql"
	"encoding/json"
	"net/http"
	"sync"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	httpSwagger "github.com/swaggo/http-swagger"

	_ "bia-energy/backend/docs" // generated by `swag init`; registers the spec that httpSwagger.WrapHandler serves
	"bia-energy/backend/internal/ai"
)

// Deps are the dependencies every handler needs. Kept as one small struct
// (rather than package-level globals) so tests can construct their own.
type Deps struct {
	DB        *sql.DB
	Explainer ai.Explainer

	// AlertPublisher is nil unless USE_FIREBASE_ALERTS is on (see
	// cmd/api/main.go); publishCriticalAlerts in alerts.go treats a nil
	// value as "alerts disabled" and is a no-op.
	AlertPublisher CriticalAlertPublisher

	mu       sync.Mutex
	analyses map[string]*analysisState
}

// NewRouter builds the chi router with all 8 endpoints from the plan doc.
func NewRouter(d *Deps) http.Handler {
	if d.analyses == nil {
		d.analyses = make(map[string]*analysisState)
	}

	r := chi.NewRouter()
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)
	r.Use(corsMiddleware)

	r.Get("/health", d.handleHealth)

	// Swagger UI, generated from the @-annotations on each handler below by
	// `swag init` (see backend/README.md). /swagger/index.html is the page
	// a person opens in a browser; /swagger/doc.json is the raw OpenAPI spec.
	r.Get("/swagger/*", httpSwagger.WrapHandler)

	r.Get("/dashboard/summary", d.handleDashboardSummary)

	r.Get("/meters", d.handleListMeters)
	r.Get("/meters/{id}", d.handleGetMeter)
	r.Get("/meters/{id}/readings", d.handleGetMeterReadings)

	r.Post("/ai/analyze", d.handlePostAnalyze)
	r.Get("/ai/analysis/{id}", d.handleGetAnalysis)

	r.Get("/anomalies", d.handleListAnomalies)
	r.Get("/anomalies/{id}", d.handleGetAnomaly)

	return r
}

func corsMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Content-Type")
		if r.Method == http.MethodOptions {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		next.ServeHTTP(w, r)
	})
}

func writeJSON(w http.ResponseWriter, status int, v interface{}) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

func writeError(w http.ResponseWriter, status int, msg string) {
	writeJSON(w, status, map[string]string{"error": msg})
}

// handleHealth reports liveness. Kept as a named method (rather than the
// inline closure this used to be) purely so swaggo has a function to
// attach @-annotations to.
//
// @Summary      Estado del servicio
// @Description  Verificación simple de disponibilidad (liveness check).
// @Tags         health
// @Produce      json
// @Success      200  {object}  HealthResponse
// @Router       /health [get]
func (d *Deps) handleHealth(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, HealthResponse{Status: "ok", Service: "bia-energy-api"})
}
